run:
  timeout: 5m

linters:
  disable:
    - typecheck  # Disable typecheck to avoid go:embed issues in CI

issues:
  exclude-dirs:
    - ui
    - ui/build
    - ui/src
    - ui/public
    - ui/node_modules
    - docs
    - scripts
    - helm
  max-issues-per-linter: 0
  max-same-issues: 0
