version: 1

run:
  timeout: 5m
  skip-dirs:
    - ui
    - ui/build
    - ui/src
    - ui/public
    - ui/node_modules
    - docs
    - scripts
    - helm
    - .git

output:
  format: colored-line-number

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 