version: 2

run:
  timeout: 5m

issues:
  exclude-dirs:
    - ui
    - ui/build
    - ui/src
    - ui/public
    - ui/node_modules
    - docs
    - scripts
    - helm
  max-issues-per-linter: 0
  max-same-issues: 0
