# Mimir Limit Optimizer Configuration - PERFORMANCE OPTIMIZED
mode: dry-run
bufferPercentage: 20.0
updateInterval: 30s  # Faster updates for responsive dashboard

# Mimir cluster configuration
mimir:
  namespace: mimir
  configMapName: mimir-runtime-overrides
  triggerRollout: false
  rolloutComponents:
    - ingester
    - querier
    - query-frontend

# Tenant scoping
tenantScoping:
  skipList: []
  includeList: []
  useRegex: false

# Dynamic limits configuration
dynamicLimits:
  enabled: true
  defaultBuffer: 20.0
  autoDetect: true

# Cost control - optimized for performance
costControl:
  enabled: false  # Disabled for better performance in standalone mode
  costMethod: composite
  costPerUnit: 0.001

# Circuit breaker for protection
circuitBreaker:
  enabled: false  # Disabled in dry-run mode
  runtimeEnabled: false
  mode: auto

# Health scanner configuration - NEW
healthScanner:
  enabled: false  # Disabled for better performance - enable only if needed
  timeout: 60s    # Overall scan timeout
  resourceTimeouts:
    secrets: 10s
    deployments: 15s
    pods: 20s
    services: 10s
    configmaps: 10s

# Audit logging - optimized settings
auditLog:
  enabled: true
  storageType: "memory"  # Memory storage for faster operations
  maxEntries: 1000       # Reduced for better performance
  configMapName: "mimir-limit-optimizer-audit"
  
  # Fast retention policies
  retention:
    retentionPeriod: "72h"        # 3 days
    maxEntries: 1000              
    maxSizeBytes: 409600          # 400KB for faster operations
    cleanupInterval: "30m"        # Cleanup every 30 minutes
    cleanupBatchSize: 50          
    emergencyThresholdPercent: 90.0

# Web UI configuration - performance optimized
ui:
  enabled: true
  port: 8082

# Synthetic data for fast standalone mode
synthetic:
  enabled: true 