# Mimir Limit Optimizer Configuration
mode: dry-run
bufferPercentage: 20.0
updateInterval: 5m

# Mimir cluster configuration
mimir:
  namespace: mimir
  configMapName: mimir-runtime-overrides
  triggerRollout: false
  rolloutComponents:
    - ingester
    - querier
    - query-frontend

# Tenant scoping
tenantScoping:
  skipList: []
  includeList: []
  useRegex: false

# Dynamic limits configuration
dynamicLimits:
  enabled: true
  defaultBuffer: 20.0
  autoDetect: true

# Cost control
costControl:
  enabled: true
  costMethod: composite
  costPerUnit: 0.001

# Circuit breaker for protection
circuitBreaker:
  enabled: false  # Disabled in dry-run mode
  runtimeEnabled: false
  mode: auto

# Audit logging
auditLog:
  enabled: true
  storageType: "configmap"  # "memory", "configmap", or "external"
  maxEntries: 2000         # Maximum entries (fallback limit)
  configMapName: "mimir-limit-optimizer-audit"
  
  # Comprehensive retention policies
  retention:
    retentionPeriod: "168h"        # 7 days (time-based retention)
    maxEntries: 2000               # Override maxEntries above
    maxSizeBytes: 819200           # 800KB (safe margin under 1MB ConfigMap limit)
    cleanupInterval: "1h"          # Cleanup every hour
    cleanupBatchSize: 100          # Process 100 entries at a time
    emergencyThresholdPercent: 90.0 # Emergency cleanup at 90% capacity 