# Debug Configuration for Mimir Limit Optimizer
# This config has extensive logging to debug blank audit log changes

# Operating mode - keep as dry-run for debugging
mode: dry-run
bufferPercentage: 20.0
updateInterval: 30s  # Short interval for quick debugging

# Mimir cluster configuration  
mimir:
  namespace: mimir
  configMapName: mimir-runtime-overrides
  triggerRollout: false
  rolloutComponents: []

# Tenant scoping - allow all tenants for debugging
tenantScoping:
  skipList: []          # Don't skip any tenants
  includeList: []       # Include all tenants
  useRegex: false

# Enable metrics endpoint - UPDATE THIS to your actual endpoint
metricsEndpoint: "http://prometheus.monitoring.svc.cluster.local:9090"

# Metrics discovery configuration - ENABLE for debugging
metricsDiscovery:
  enabled: true         # Enable to see what gets discovered
  namespace: mimir      # Your Mimir namespace
  serviceLabelSelector: "app.kubernetes.io/part-of=mimir"
  serviceNames:
    - "mimir-distributor"
    - "mimir-ingester"
    - "mimir-querier" 
    - "mimir-query-frontend"
    - "mimir-compactor"
    - "mimir-store-gateway"
  metricsPath: "/metrics"
  portName: "http-metrics"
  port: 8080
  
  # Multi-tenant configuration
  tenantDiscovery:
    metricsTenantID: "couwatch"    # Your tenant ID
    tenantHeaders:
      X-Scope-OrgID: "couwatch"    # Multi-tenant header
    fallbackTenants:               # Fallback tenants for testing
      - "couwatch"
      - "test-tenant-1"
      - "test-tenant-2"
    configMapNames:
      - "mimir-runtime-overrides"   # Parse existing ConfigMap for tenants
    enableSynthetic: true          # Enable synthetic tenants as backup
    syntheticCount: 2

# Trend analysis - 48h lookback
trendAnalysis:
  analysisWindow: "48h"
  percentile: 95.0
  useMovingAverage: true
  includePeaks: true

# Event spike detection
eventSpike:
  enabled: true
  threshold: 2.0
  detectionWindow: "5m"
  cooldownPeriod: "30m"
  maxSpikeMultiplier: 5.0

# CRITICAL: Dynamic limits configuration - MUST BE PROPERLY CONFIGURED
dynamicLimits:
  enabled: true                    # Enable dynamic limits
  defaultBuffer: 20.0
  autoDetect: true                # Auto-detect available limits
  
  # Explicit limit definitions to ensure they're enabled
  limitDefinitions:
    ingestion_rate:
      enabled: true
      type: "rate"
      minValue: 1000
      maxValue: 1000000
      bufferFactor: 20.0
    
    ingestion_burst_size:
      enabled: true  
      type: "size"
      minValue: 10000
      maxValue: 10000000
      bufferFactor: 20.0
    
    max_global_series_per_user:
      enabled: true
      type: "count" 
      minValue: 10000
      maxValue: 10000000
      bufferFactor: 20.0
    
    max_samples_per_query:
      enabled: true
      type: "count"
      minValue: 100000
      maxValue: 100000000
      bufferFactor: 20.0
    
    max_series_per_query:
      enabled: true
      type: "count"
      minValue: 10000
      maxValue: 1000000
      bufferFactor: 20.0

# Audit logging - ConfigMap storage for persistence
auditLog:
  enabled: true
  storageType: configmap           # Use ConfigMap for persistent logs
  configMapName: mimir-limit-optimizer-audit
  maxEntries: 1000

# Cost control - disabled for debugging
costControl:
  enabled: false

# Circuit breaker - disabled for debugging  
circuitBreaker:
  enabled: false
  runtimeEnabled: false
  mode: auto

# Synthetic mode - backup data source
synthetic:
  enabled: true                    # Enable as fallback
  tenantCount: 3 