mode: dry-run
bufferPercentage: 20.0
updateInterval: 30s

# Use direct endpoint with tenant configuration
metricsEndpoint: "http://query-frontend.mimir.svc.cluster.local:8080/api/v1/query?query=up"

# Metrics discovery configuration
metricsDiscovery:
  enabled: false
  tenantDiscovery:
    metricsTenantID: "couwatch"
    tenantHeaders:
      X-Scope-OrgID: "couwatch"
    fallbackTenants:
      - "couwatch"
    enableSynthetic: false

# Disable resource-intensive features for testing
costControl:
  enabled: false

circuitBreaker:
  enabled: false

dynamicLimits:
  enabled: true
  defaultBuffer: 20.0
  autoDetect: false

auditLog:
  enabled: false

synthetic:
  enabled: false 