apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mimir-limit-optimizer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir-limit-optimizer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mimir-limit-optimizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mimir-limit-optimizer.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mimir-limit-optimizer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
        - --config=/etc/config/config.yaml
        - --metrics-bind-address=0.0.0.0:{{ .Values.metrics.port }}
        - --health-probe-bind-address=0.0.0.0:8081
        - --log-level={{ .Values.logging.level }}
        {{- if .Values.leaderElection.enabled }}
        - --leader-elect
        {{- end }}
        {{- with .Values.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        {{- if .Values.healthProbes.liveness.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: {{ .Values.healthProbes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthProbes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthProbes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.healthProbes.liveness.failureThreshold }}
        {{- end }}
        {{- if .Values.healthProbes.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: {{ .Values.healthProbes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthProbes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthProbes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.healthProbes.readiness.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: tmp
          mountPath: /tmp
        {{- with .Values.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "mimir-limit-optimizer.fullname" . }}-config
      - name: tmp
        emptyDir: {}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 