---
{{- if .Values.rbac.create}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{include "mimir-limit-optimizer.fullname" .}}
  labels:
    {{- include "mimir-limit-optimizer.labels" . | nindent 4}}
rules:
  # ConfigMap permissions for runtime overrides
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  # Service discovery permissions
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]

  # Deployment management for triggering rollouts
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]

  # Leader election permissions
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Event creation for informational purposes
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{include "mimir-limit-optimizer.fullname" .}}
  labels:
    {{- include "mimir-limit-optimizer.labels" . | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{include "mimir-limit-optimizer.fullname" .}}
subjects:
  - kind: ServiceAccount
    name: {{include "mimir-limit-optimizer.serviceAccountName" .}}
    namespace: {{.Release.Namespace}}

---
# Additional role for managing audit ConfigMaps in the controller's namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{include "mimir-limit-optimizer.fullname" .}}-audit
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "mimir-limit-optimizer.labels" . | nindent 4}}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    resourceNames: ["{{.Values.auditLog.configMapName}}"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{include "mimir-limit-optimizer.fullname" .}}-audit
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "mimir-limit-optimizer.labels" . | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{include "mimir-limit-optimizer.fullname" .}}-audit
subjects:
  - kind: ServiceAccount
    name: {{include "mimir-limit-optimizer.serviceAccountName" .}}
    namespace: {{.Release.Namespace}}
{{- end}} 