{{- if and .Values.serviceMonitor.enabled .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mimir-limit-optimizer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir-limit-optimizer.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mimir-limit-optimizer.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http-metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: {{ .Values.metrics.path }}
    scheme: http
{{- end }} 