---
apiVersion: v1
kind: Service
metadata:
  name: {{include "mimir-limit-optimizer.fullname" .}}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "mimir-limit-optimizer.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
  - port: {{.Values.service.port}}
    targetPort: metrics
    protocol: TCP
    name: http-metrics
  selector:
    {{- include "mimir-limit-optimizer.selectorLabels" . | nindent 4}} 