name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - AkshayDubey29

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Mimir Limit Optimizer are you running?
      placeholder: "e.g., v1.0.0, latest, main branch"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe what happened..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe what you expected..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - Kubernetes version:
        - Mimir version:
        - Operating System:
        - Deployment method (Helm/kubectl):
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please provide your configuration (sanitized - remove secrets)
      render: yaml
      placeholder: |
        # Your configuration here
        config:
          mode: "dry-run"
          # ...

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide relevant log output
      render: shell
      placeholder: |
        # Controller logs
        kubectl logs -n mimir-limit-optimizer deployment/mimir-limit-optimizer

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 